name             'my-app'
maintainer       'Sergio Márquez'
maintainer_email 'smarquezs@gmail.com'
license          'All rights reserved'
description      'Installs/Configures my-app'
long_description 'Installs/Configures my-app'
version          '0.1.0'
depends          'mysql'
depends          'rbenv'
depends          'ruby_build'
depends          'ohai'
depends          'nginx'
depends          'imagemagick'

