source "https://supermarket.getchef.com"

cookbook "sqlite"
cookbook 'mysql'
cookbook 'openssl'
cookbook 'nginx', '2.4.2'
cookbook 'ruby_build'
cookbook 'rbenv', git: 'git@github.com:fnichol/chef-rbenv.git'
cookbook 'imagemagick'
